---
version: 0.2.3
slug: silabs_flasher
name: Silicon Labs Flasher
description: Silicon Labs firmware flasher add-on
url: >
  https://github.com/jdbwlj/efr32-flasher-bootloader/edit/main/tzb-silabs-flasher
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
gpio: false
hassio_api: true
image: homeassistant/{arch}-addon-silabs-flasher
init: false
options:
  network_device: null
  device: null
  device_type: false
  firmware_url: str?
  bootloader_baudrate: "115200"
  flow_control: false
  verbose: false
schema:
  network_device: str?
  device: device(subsystem=tty)?
  device_type: bool?
  firmware_url: str?
  bootloader_baudrate: list(57600|115200|230400|460800|921600)
  flow_control: bool?
  verbose: bool?
stage: experimental
startup: once
boot: manual
